#!/bin/bash

./emit_logs.py
./emit_logs.py error 2nd..
./emit_logs.py
./emit_logs.py warning 4th....
./emit_logs.py
./emit_logs.py error 6th......
./emit_logs.py
./emit_logs.py warning 8th........
./emit_logs.py error 9th.........
./emit_logs.py
./emit_logs.py
./emit_logs.py error B-6th......
./emit_logs.py warning B-7th.......
./emit_logs.py 
./emit_logs.py warning B-9th.........
./emit_logs.py warning B-10th..........
./emit_logs.py error B-11th...........
