#!/bin/bash

./fanout_logs.py First.
./fanout_logs.py 2nd..
./fanout_logs.py 3rd...
./fanout_logs.py 4th....
./fanout_logs.py 5th.....
./fanout_logs.py 6th......
./fanout_logs.py 7th.......
./fanout_logs.py 8th........
./fanout_logs.py 9th.........
./fanout_logs.py 10th..........
./fanout_logs.py 11th...........
./fanout_logs.py B-First.
./fanout_logs.py B-2nd..
./fanout_logs.py B-3rd...
./fanout_logs.py B-4th....
./fanout_logs.py B-5th.....
./fanout_logs.py B-6th......
./fanout_logs.py B-7th.......
./fanout_logs.py B-8th........
./fanout_logs.py B-9th.........
./fanout_logs.py B-10th..........
./fanout_logs.py B-11th...........
